server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studymate
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: trace